# Generated by Django 4.2.5 on 2023-09-10 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_seen'),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendoffer',
            name='notification',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notifications.notification'),
            preserve_default=False,
        ),
    ]
